
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ifta_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: id
#            client-secret: secret
#          google:
#            client-id: your-id.apps.googleusercontent.com
#            client-secret: your-secret